# Generated by Django 2.1.3 on 2018-11-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wp', '0002_auto_20181111_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Cource Title')),
                ('contact', models.CharField(max_length=200, verbose_name='Contacts')),
                ('descript', models.TextField(max_length=500, verbose_name='Cource Description')),
            ],
        ),
        migrations.AlterField(
            model_name='vac',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='vac',
            name='desc',
            field=models.TextField(default='', max_length=400, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vac',
            name='empler',
            field=models.CharField(default='', max_length=200, verbose_name='Employer'),
        ),
        migrations.AlterField(
            model_name='vac',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='vac',
            name='salary',
            field=models.IntegerField(blank=True, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='vac',
            name='skills',
            field=models.CharField(default='', max_length=200, verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='vac',
            name='sphere',
            field=models.CharField(default='', max_length=200, verbose_name='Sphere'),
        ),
    ]
