# Generated by Django 2.1.3 on 2018-11-11 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wp', '0003_auto_20181111_1526'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coursec',
            new_name='Course',
        ),
    ]
