# Generated by Django 2.1.3 on 2018-11-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wp', '0004_auto_20181111_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sphere',
            field=models.CharField(default='', max_length=200, verbose_name='Sphere'),
        ),
        migrations.AlterField(
            model_name='course',
            name='descript',
            field=models.TextField(max_length=500, verbose_name='Course Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Course Title'),
        ),
    ]
